name: CI
on:
  push:
    branches: [ master ]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm i

      - name: Run project
        run: npm start
